/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Pt */
        post: operations["register_pt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Pt */
        post: operations["login_pt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Dr */
        post: operations["register_dr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Dr */
        post: operations["login_dr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctors */
        get: operations["get_doctors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctor */
        get: operations["get_doctor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book */
        post: operations["book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/cancel/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Booking */
        delete: operations["cancel_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Initial */
        get: operations["get_initial"];
        put?: never;
        /** Stream Chat */
        post: operations["stream_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/from_template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root Path */
        get: operations["root_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppointmentResponse */
        AppointmentResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Patient Id */
            patient_id: string;
            slot: components["schemas"]["Slot"];
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Scheduled Date
             * Format: date-time
             */
            scheduled_date: string;
            status: components["schemas"]["AppointmentStatus"];
            /**
             * Clinic Id
             * Format: uuid
             */
            clinic_id: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * AppointmentStatus
         * @enum {string}
         */
        AppointmentStatus: "active" | "completed" | "cancelled" | "missed";
        /** Body_create_doctors_onboard_post */
        Body_create_doctors_onboard_post: {
            /** Name */
            name: string;
            /**
             * Gender
             * @enum {string}
             */
            gender: "male" | "female";
            /** Degree */
            degree: string;
            /** Medical College */
            medical_college: string;
            /** Graduation Year */
            graduation_year: number;
            /** License Number */
            license_number: string;
            /** Primary Specialization */
            primary_specialization: string;
            /** Experience */
            experience: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Secondary Focus Areas
             * @default []
             */
            secondary_focus_areas: string[] | string;
            /** Bio */
            bio?: string | null;
            /** Phone */
            phone?: string | null;
            /** Profile */
            profile?: string | null;
        };
        /** Body_get_clinics_get */
        Body_get_clinics_get: {
            pagination_params: components["schemas"]["PaginationParams"];
            filter_params: components["schemas"]["ClinicRouteFilters"];
        };
        /** Body_register_dr_auth_register_doctor_post */
        Body_register_dr_auth_register_doctor_post: {
            /** Name */
            name: string;
            /**
             * Gender
             * @enum {string}
             */
            gender: "male" | "female";
            /** Degree */
            degree: string;
            /** Medical College */
            medical_college: string;
            /** Graduation Year */
            graduation_year: number;
            /** License Number */
            license_number: string;
            /** Primary Specialization */
            primary_specialization: string;
            /** Experience */
            experience: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Secondary Focus Areas
             * @default []
             */
            secondary_focus_areas: string[] | string;
            /** Bio */
            bio?: string | null;
            /** Phone */
            phone?: string | null;
            /** Profile */
            profile?: string | null;
        };
        /** BookingRequestData */
        BookingRequestData: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /**
             * Doctorid
             * Format: uuid
             */
            doctorId: string;
            /**
             * Slotid
             * Format: uuid
             */
            slotId: string;
        } & {
            [key: string]: unknown;
        };
        /** Clinic */
        Clinic: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Owner */
            owner?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Facilities
             * @default []
             */
            facilities: string[];
            /** Pincode */
            pincode?: number | null;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Contacts
             * @default []
             */
            contacts: number[];
            /** Rating */
            readonly rating: number;
        } & {
            [key: string]: unknown;
        };
        /** ClinicRouteFilters */
        ClinicRouteFilters: {
            /** Searchquery */
            searchQuery?: string | null;
            /** Minrating */
            minRating?: number | null;
            /** Maxdistance */
            maxDistance?: number | null;
            /** Facilities */
            facilities?: string[] | null;
        };
        /** Doctor */
        Doctor: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Specialization */
            primary_specialization: string;
            /** Experience */
            experience: number;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** @default unknown */
            status: components["schemas"]["Status"] | null;
            /**
             * Consults Online
             * @default false
             */
            consults_online: boolean;
            /**
             * Booking Enabled
             * @default false
             */
            booking_enabled: boolean;
            /**
             * Secondary Focus Areas
             * @default []
             */
            secondary_focus_areas: string[];
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["Schedule"][];
            /** Image */
            image?: string | null;
            gender: components["schemas"]["Gender"];
            /** Credentials */
            credentials: string;
            /** Rating */
            readonly rating: number;
            /** Image Url */
            readonly image_url: string | null;
        } & {
            [key: string]: unknown;
        };
        /** DoctorLogin */
        DoctorLogin: {
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            /** Id */
            id?: string | null;
        };
        /** DrProfileResponse */
        DrProfileResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Specialization */
            primary_specialization: string;
            /** Experience */
            experience: number;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** @default unknown */
            status: components["schemas"]["Status"] | null;
            /**
             * Consults Online
             * @default false
             */
            consults_online: boolean;
            /**
             * Booking Enabled
             * @default false
             */
            booking_enabled: boolean;
            /**
             * Secondary Focus Areas
             * @default []
             */
            secondary_focus_areas: string[];
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["Schedule"][];
            /** Image */
            image?: string | null;
            gender: components["schemas"]["Gender"];
            /** Credentials */
            credentials: string;
            /** College Studied */
            college_studied?: string | null;
            /** Graduation Year */
            graduation_year?: number | null;
            /**
             * Bio
             * @default
             */
            bio: string | null;
            /** License Number */
            license_number: string;
            /** Rating */
            readonly rating: number;
            /** Image Url */
            readonly image_url: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "male" | "female";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageRequest */
        MessageRequest: {
            /** @default user */
            role: components["schemas"]["Role"];
            /** Content */
            content: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "online" | "in person";
        /** PaginatedResponse[Clinic] */
        PaginatedResponse_Clinic_: {
            /** Entities */
            entities: components["schemas"]["Clinic"][];
            /** Count */
            count: number;
            /** Has Next */
            has_next?: boolean | null;
            /**
             * Has Prev
             * @default false
             */
            has_prev: boolean;
        };
        /** PaginatedResponse[Doctor] */
        PaginatedResponse_Doctor_: {
            /** Entities */
            entities: components["schemas"]["Doctor"][];
            /** Count */
            count: number;
            /** Has Next */
            has_next?: boolean | null;
            /**
             * Has Prev
             * @default false
             */
            has_prev: boolean;
        };
        /** PaginationParams */
        PaginationParams: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Max
             * @default 10
             */
            max: number;
            /**
             * Sortby
             * @default name
             */
            sortBy: ("rating" | "reviews" | "experience" | "fee" | "name") | null;
            /** @default asc */
            sortOrder: components["schemas"]["SortOrder"] | null;
        };
        /** PatientCreate */
        PatientCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PatientLogin */
        PatientLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PatientProfileResponse */
        PatientProfileResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username?: string | null;
            /**
             * Appointments
             * @default []
             */
            appointments: components["schemas"]["AppointmentResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** Review */
        Review: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
            entity: components["schemas"]["ReviewableEntity"];
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Appointment Id */
            appointment_id?: string | null;
            /** Patient Id */
            patient_id: string;
        };
        /**
         * ReviewableEntity
         * @enum {string}
         */
        ReviewableEntity: "DOCTOR" | "CLINIC";
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "system" | "assistant" | "developer";
        /** Schedule */
        Schedule: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /**
             * Base Slot Duration
             * @default 20
             */
            base_slot_duration: number | null;
            /**
             * Clinic Id
             * Format: uuid
             */
            clinic_id: string;
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            clinic?: components["schemas"]["Clinic"] | null;
            /**
             * Slots
             * @default []
             */
            slots: components["schemas"]["Slot"][];
        } & {
            [key: string]: unknown;
        };
        /** Slot */
        Slot: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Duration */
            duration: number;
            /**
             * Is Booked
             * @default false
             */
            is_booked: boolean;
            mode?: components["schemas"]["Mode"] | null;
            /**
             * Slot Datetime
             * Format: date-time
             */
            slot_datetime: string;
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * Status
         * @enum {string}
         */
        Status: "away" | "available" | "in_patient" | "unknown";
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Username */
            username?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_pt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_pt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_dr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_register_dr_auth_register_doctor_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_dr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrProfileResponse"] | components["schemas"]["PatientProfileResponse"];
                };
            };
        };
    };
    get_doctors: {
        parameters: {
            query?: {
                searchQuery?: string | null;
                minRating?: number | null;
                maxDistance?: number | null;
                consultsOnline?: "1" | null;
                currentlyAvailable?: "1" | null;
                specialization?: string | null;
                experience?: number | null;
                page?: number;
                max?: number;
                sortBy?: ("rating" | "reviews" | "experience" | "fee" | "name") | null;
                sortOrder?: components["schemas"]["SortOrder"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Doctor_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_doctors_onboard_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequestData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_get_clinics_get"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Clinic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_initial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_path: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
