/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctors */
        get: operations["get_doctors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctor */
        get: operations["get_doctor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book */
        post: operations["book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/cancel/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Booking */
        delete: operations["cancel_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Chat */
        post: operations["stream_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root Path */
        get: operations["root_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate Data */
        get: operations["generate_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Appointment */
        Appointment: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Patient Id */
            patient_id: string;
            slot: components["schemas"]["Slot"];
            /**
             * Scheduled Date
             * Format: date-time
             */
            scheduled_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            status: components["schemas"]["AppointmentStatus"];
        } & {
            [key: string]: unknown;
        };
        /**
         * AppointmentStatus
         * @enum {string}
         */
        AppointmentStatus: "active" | "completed" | "cancelled";
        /** BookingRequestData */
        BookingRequestData: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /**
             * Doctorid
             * Format: uuid
             */
            doctorId: string;
            /**
             * Slotid
             * Format: uuid
             */
            slotId: string;
        } & {
            [key: string]: unknown;
        };
        /** ChatMessageRequest */
        ChatMessageRequest: {
            /** @default user */
            role: components["schemas"]["Role"];
            /** Message */
            message: string;
        } & {
            [key: string]: unknown;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            role: components["schemas"]["Role"];
            /** Message */
            message: string;
        } & {
            [key: string]: unknown;
        };
        /** Clinic */
        Clinic: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Owner
             * Format: uuid
             */
            owner: string;
            /** Location */
            location: string;
            /** Facilities */
            facilities: string[];
            /** Pincode */
            pincode: number;
            /**
             * Reviews
             * @default 0
             */
            reviews: number;
            /** Rating */
            rating: number;
            /**
             * Contacts
             * @default []
             */
            contacts: number[];
        } & {
            [key: string]: unknown;
        };
        /** CreateUser */
        CreateUser: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Doctor */
        Doctor: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Fee */
            fee: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Rating */
            rating: number;
            /** Reviews */
            reviews: number;
            status: components["schemas"]["Status"];
            /** Experience */
            experience: number;
            /** Credentials */
            credentials: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** Primary Specialization */
            primary_specialization: string;
            /**
             * Consults Online
             * @default false
             */
            consults_online: boolean;
            /**
             * Booking Enabled
             * @default false
             */
            booking_enabled: boolean;
            /** Base Consult Time */
            base_consult_time?: number | null;
            /**
             * Currently Available
             * @default false
             */
            currently_available: boolean;
            /**
             * Secondary Specializations
             * @default []
             */
            secondary_specializations: string[];
            /** Last Updated */
            last_updated?: string | null;
            /** Next Available */
            next_available?: string | null;
            office?: components["schemas"]["Clinic"] | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["Schedule"][];
        } & {
            [key: string]: unknown;
        };
        /** DoctorSummary */
        DoctorSummary: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Fee */
            fee: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Rating */
            rating: number;
            /** Reviews */
            reviews: number;
            status: components["schemas"]["Status"];
            /** Experience */
            experience: number;
            /** Credentials */
            credentials: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** Primary Specialization */
            primary_specialization: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginUser */
        LoginUser: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "online" | "in person";
        /** PaginatedResponse[Clinic] */
        PaginatedResponse_Clinic_: {
            /** Entities */
            entities: components["schemas"]["Clinic"][];
            /** Count */
            count: number;
            /** Has Next */
            has_next?: boolean | null;
            /**
             * Has Prev
             * @default false
             */
            has_prev: boolean;
        };
        /** PaginatedResponse[DoctorSummary] */
        PaginatedResponse_DoctorSummary_: {
            /** Entities */
            entities: components["schemas"]["DoctorSummary"][];
            /** Count */
            count: number;
            /** Has Next */
            has_next?: boolean | null;
            /**
             * Has Prev
             * @default false
             */
            has_prev: boolean;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "system" | "assistant";
        /**
         * Schedule
         * @description use datetime as main schedule date getter if doctors
         *     don't seem to have a fixed schedule, else better off with weekdays
         */
        Schedule: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Weekdays */
            weekdays: number[];
            /** Is Active */
            is_active: boolean;
            /** Is Recurring */
            is_recurring: boolean;
            /**
             * Clinic Id
             * Format: uuid
             */
            clinic_id: string;
            /**
             * Doctor Id
             * Format: uuid
             */
            doctor_id: string;
            clinic?: components["schemas"]["Clinic"] | null;
            /** Slots */
            slots: components["schemas"]["Slot"][];
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /** Hours Available */
            hours_available?: number | null;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
        } & {
            [key: string]: unknown;
        };
        /** Slot */
        Slot: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Duration */
            duration: number;
            /**
             * Booked
             * @default false
             */
            booked: boolean;
            mode?: components["schemas"]["Mode"] | null;
            /**
             * Begin
             * Format: time
             * @description The slot start time
             */
            begin: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * Status
         * @enum {string}
         */
        Status: "away" | "available" | "in_patient" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_doctors: {
        parameters: {
            query?: {
                searchQuery?: string | null;
                minRating?: number | null;
                maxDistance?: number | null;
                consults_online?: "1" | null;
                currentlyAvailable?: "1" | null;
                specialization?: string | null;
                page?: number;
                max?: number;
                sortBy?: ("rating" | "reviews" | "experience" | "fee" | "name") | null;
                sortOrder?: components["schemas"]["SortOrder"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DoctorSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequestData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: {
                page?: number;
                max?: number;
                sortBy?: ("rating" | "reviews" | "experience" | "fee" | "name") | null;
                sortOrder?: components["schemas"]["SortOrder"] | null;
                searchQuery?: string | null;
                minRating?: number | null;
                maxDistance?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Clinic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_path: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
