/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Pt */
        post: operations["register_pt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Pt */
        post: operations["login_pt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Dr */
        post: operations["register_dr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Dr */
        post: operations["login_dr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Account */
        delete: operations["remove_account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctors */
        get: operations["get_doctors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctor */
        get: operations["get_doctor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book */
        post: operations["book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/cancel/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Booking */
        delete: operations["cancel_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All */
        get: operations["get_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Initial */
        get: operations["get_initial"];
        put?: never;
        /** Stream Chat */
        post: operations["stream_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/from_template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppointmentConfirmation */
        AppointmentConfirmation: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Patientid */
            patientId: string;
            /**
             * Scheduleddate
             * Format: date-time
             */
            scheduledDate: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            status: components["schemas"]["AppointmentStatus"];
        };
        /** AppointmentResponse */
        AppointmentResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Patientid */
            patientId: string;
            /**
             * Scheduleddate
             * Format: date-time
             */
            scheduledDate: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            status: components["schemas"]["AppointmentStatus"];
            /** Clinicid */
            clinicId: string;
            /** Doctorid */
            doctorId: string;
            /** Slotid */
            slotId: string;
            slot: components["schemas"]["Slot"];
            doctor: components["schemas"]["DoctorHttpMinimal"];
            clinic: components["schemas"]["ClinicHttpMinimal"];
        };
        /**
         * AppointmentStatus
         * @enum {string}
         */
        AppointmentStatus: "active" | "completed" | "cancelled" | "missed";
        /** BaseChatMessage */
        BaseChatMessage: {
            role: components["schemas"]["Role"];
            /** Content */
            content: string;
        };
        /** Body_create_doctors_onboard_post */
        Body_create_doctors_onboard_post: {
            /** Name */
            name: string;
            /**
             * Gender
             * @enum {string}
             */
            gender: "male" | "female";
            /** Degree */
            degree: string;
            /** Medical College */
            medical_college: string;
            /** Graduation Year */
            graduation_year: number;
            /** License Number */
            license_number: string;
            /** Primary Specialization */
            primary_specialization: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Experience
             * @default 0
             */
            experience: number | null;
            /**
             * Secondary Focus Areas
             * @default []
             */
            secondary_focus_areas: string[] | string;
            /** Bio */
            bio?: string | null;
            /** Phone */
            phone?: string | null;
            /** Profile */
            profile?: string | null;
        };
        /** Body_register_dr_auth_register_doctor_post */
        Body_register_dr_auth_register_doctor_post: {
            /** Name */
            name: string;
            /**
             * Gender
             * @enum {string}
             */
            gender: "male" | "female";
            /** Degree */
            degree: string;
            /** Medical College */
            medical_college: string;
            /** Graduation Year */
            graduation_year: number;
            /** License Number */
            license_number: string;
            /** Primary Specialization */
            primary_specialization: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Experience
             * @default 0
             */
            experience: number | null;
            /**
             * Secondary Focus Areas
             * @default []
             */
            secondary_focus_areas: string[] | string;
            /** Bio */
            bio?: string | null;
            /** Phone */
            phone?: string | null;
            /** Profile */
            profile?: string | null;
        };
        /** BookingRequestData */
        BookingRequestData: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /**
             * Doctorid
             * Format: uuid
             */
            doctorId: string;
            /**
             * Slotid
             * Format: uuid
             */
            slotId: string;
        };
        /** ClinicHttpFull */
        ClinicHttpFull: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Location */
            location?: string | null;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Facilities
             * @default []
             */
            facilities: string[];
            /** Owner */
            owner?: string | null;
            /** Pincode */
            pincode?: number | null;
            /**
             * Contacts
             * @default []
             */
            contacts: number[];
            /** Rating */
            readonly rating: number;
        };
        /** ClinicHttpMinimal */
        ClinicHttpMinimal: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Location */
            location?: string | null;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Facilities
             * @default []
             */
            facilities: string[];
            /** Rating */
            readonly rating: number;
        };
        /** DoctorHttpFull */
        DoctorHttpFull: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Primaryspecialization */
            primarySpecialization: string;
            /** Experience */
            experience: number;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** @default unknown */
            status: components["schemas"]["Status"] | null;
            /** Image */
            image?: string | null;
            /** Credentials */
            credentials: string;
            gender: components["schemas"]["Gender"];
            /**
             * Consultsonline
             * @default false
             */
            consultsOnline: boolean;
            /**
             * Bookingenabled
             * @default false
             */
            bookingEnabled: boolean;
            /**
             * Secondaryfocusareas
             * @default []
             */
            secondaryFocusAreas: string[];
            /** Lastupdated */
            lastUpdated?: string | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["Schedule"][];
            /** Rating */
            readonly rating: number;
            /** Imageurl */
            readonly imageUrl: string | null;
        };
        /** DoctorHttpMinimal */
        DoctorHttpMinimal: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Primaryspecialization */
            primarySpecialization: string;
            /** Experience */
            experience: number;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** @default unknown */
            status: components["schemas"]["Status"] | null;
            /** Image */
            image?: string | null;
            /** Rating */
            readonly rating: number;
            /** Imageurl */
            readonly imageUrl: string | null;
        };
        /** DoctorLogin */
        DoctorLogin: {
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            /** Id */
            id?: string | null;
        };
        /** DrProfileResponse */
        DrProfileResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name: string;
            /** Primaryspecialization */
            primarySpecialization: string;
            /** Experience */
            experience: number;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["Review"][];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** @default unknown */
            status: components["schemas"]["Status"] | null;
            /** Image */
            image?: string | null;
            /** Credentials */
            credentials: string;
            gender: components["schemas"]["Gender"];
            /**
             * Consultsonline
             * @default false
             */
            consultsOnline: boolean;
            /**
             * Bookingenabled
             * @default false
             */
            bookingEnabled: boolean;
            /**
             * Secondaryfocusareas
             * @default []
             */
            secondaryFocusAreas: string[];
            /** Lastupdated */
            lastUpdated?: string | null;
            /**
             * Schedules
             * @default []
             */
            schedules: components["schemas"]["Schedule"][];
            /** Collegestudied */
            collegeStudied?: string | null;
            /** Graduationyear */
            graduationYear?: number | null;
            /**
             * Bio
             * @default
             */
            bio: string | null;
            /** Licensenumber */
            licenseNumber: string;
            /** Rating */
            readonly rating: number;
            /** Imageurl */
            readonly imageUrl: string | null;
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "male" | "female";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "online" | "in person";
        /** PaginatedResponse[ClinicHttpMinimal] */
        PaginatedResponse_ClinicHttpMinimal_: {
            /** Entities */
            entities: components["schemas"]["ClinicHttpMinimal"][];
            /** Count */
            count: number;
            /** Hasnext */
            hasNext?: boolean | null;
        };
        /** PaginatedResponse[DoctorHttpMinimal] */
        PaginatedResponse_DoctorHttpMinimal_: {
            /** Entities */
            entities: components["schemas"]["DoctorHttpMinimal"][];
            /** Count */
            count: number;
            /** Hasnext */
            hasNext?: boolean | null;
        };
        /** PatientCreate */
        PatientCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PatientLogin */
        PatientLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PatientProfileResponse */
        PatientProfileResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username?: string | null;
            /**
             * Appointments
             * @default []
             */
            appointments: components["schemas"]["AppointmentResponse"][];
        };
        /** Review */
        Review: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
            entity: components["schemas"]["ReviewableEntity"];
            /** Entity Id */
            entity_id: string;
            /** Appointment Id */
            appointment_id?: string | null;
            /** Patient Id */
            patient_id: string;
        };
        /**
         * ReviewableEntity
         * @enum {string}
         */
        ReviewableEntity: "DOCTOR" | "CLINIC";
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "system" | "assistant" | "tool";
        /** Schedule */
        Schedule: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /**
             * Base Slot Duration
             * @default 20
             */
            base_slot_duration: number | null;
            /** Clinic Id */
            clinic_id: string;
            /** Doctor Id */
            doctor_id: string;
            clinic?: components["schemas"]["ClinicHttpMinimal"] | null;
            /**
             * Slots
             * @default []
             */
            slots: components["schemas"]["Slot"][];
        };
        /** Slot */
        Slot: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /** Duration */
            duration: number;
            /**
             * Is Booked
             * @default false
             */
            is_booked: boolean;
            mode?: components["schemas"]["Mode"] | null;
            /**
             * Slot Datetime
             * Format: date-time
             */
            slot_datetime: string;
            /** Schedule Id */
            schedule_id: string;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * Status
         * @enum {string}
         */
        Status: "away" | "available" | "in_patient" | "unknown";
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * @description the unique identifier of the record
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Username */
            username?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_pt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_pt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_dr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_register_dr_auth_register_doctor_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_dr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrProfileResponse"] | components["schemas"]["PatientProfileResponse"] | null;
                };
            };
        };
    };
    remove_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_doctors: {
        parameters: {
            query?: {
                searchQuery?: string | null;
                minRating?: number | null;
                maxDistance?: number | null;
                consultsOnline?: "1" | null;
                currentlyAvailable?: "1" | null;
                specialization?: string | null;
                experience?: number | null;
                fee?: number | null;
                gender?: components["schemas"]["Gender"] | null;
                page?: number;
                max?: number;
                sortBy?: string | null;
                sortOrder?: components["schemas"]["SortOrder"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DoctorHttpMinimal_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorHttpFull"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_doctors_onboard_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorHttpMinimal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequestData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentConfirmation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all: {
        parameters: {
            query?: {
                page?: number;
                max?: number;
                sortBy?: string | null;
                sortOrder?: components["schemas"]["SortOrder"] | null;
                searchQuery?: string | null;
                minRating?: number | null;
                maxDistance?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ClinicHttpMinimal_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicHttpFull"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_initial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BaseChatMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BaseChatMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
