export const SPECIALIZATIONS = [
  "Cardiology",
  "Neurology",
  "Orthopedics",
  "Dermatology",
  "Pediatrics",
  "Psychiatry",
  "Ophthalmology",
  "ENT",
  "General Medicine",
  "Gastroenterology",
  "Pulmonology",
  "Nephrology",
  "Endocrinology",
  "Oncology",
  "Urology",
  "Gynecology & Obstetrics",
  "Rheumatology",
  "Hematology",
  "Infectious Disease",
  "Emergency Medicine",
  "Anesthesiology",
  "Radiology",
  "Pathology",
  "General Surgery",
  "Plastic Surgery",
  "Neurosurgery",
  "Cardiothoracic Surgery",
  "Vascular Surgery",
  "Dentistry",
  "Physiotherapy",
  "Dietetics & Nutrition",
  "Ayurveda",
  "Homeopathy",
];

export const WEEKDAYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
] as const;
