"""Initial revision...

Revision ID: 4d3a3d8dcb2e
Revises: 
Create Date: 2026-03-13 15:56:43.136966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d3a3d8dcb2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'PATIENT', 'CLINIC', 'GUEST', name='user_role'), server_default=sa.text("'PATIENT'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('clinic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=2), server_default='0.0', nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(length=10), nullable=False),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.CheckConstraint('rating >= 0.0 and rating <= 5.0', name='chk_clinic_rating'),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=2), server_default='0.0', nullable=False),
    sa.Column('reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('primary_specialization', sa.String(), nullable=False),
    sa.Column('secondary_specializations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('consults_online', sa.Boolean(), nullable=False),
    sa.Column('currently_available', sa.Boolean(), nullable=False),
    sa.Column('next_available', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AWAY', 'AVAILABLE', 'IN_PATIENT', 'UNKNOWN', name='doctor_availability_status'), nullable=False),
    sa.CheckConstraint('rating >= 0.0 and rating <= 5.0', name='chk_doctor_rating'),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_clinics',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'clinic_id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_available', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('base_slot_duration', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='chk_schedule_timing'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('begin', sa.Time(), nullable=False),
    sa.Column('mode', sa.Enum('ONLINE', 'IN_PERSON', name='consultation_mode'), server_default=sa.text("'IN_PERSON'"), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.Column('guest_contact', sa.String(length=10), nullable=True),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='appointment_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(patient_id IS NOT NULL) or (guest_name IS NOT NULL)', name='chk_patient_identity'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('slot')
    op.drop_table('schedule')
    op.drop_table('doctor_clinics')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('clinic')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
