"""initial schema

Revision ID: 9ce845c61670
Revises: 
Create Date: 2026-10-02 10:13:14.304799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9ce845c61670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('owner', sa.String(), nullable=True),
                    sa.Column('pincode', sa.String(length=6), nullable=True),
                    sa.Column('location', sa.VARCHAR(), nullable=False),
                    sa.Column('whatsapp', sa.String(length=10), nullable=True),
                    sa.Column('contact_numbers', sa.ARRAY(sa.String(length=10)),
                              server_default='{}', nullable=False),
                    sa.Column('facilities', sa.JSON(),
                              server_default='[]', nullable=True),
                    sa.Column('specializations', sa.JSON(),
                              server_default='[]', nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clinic_name'), 'clinic', ['name'], unique=True)
    op.create_table('doctor',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(length=10), nullable=True),
                    sa.Column('image', sa.Text(), nullable=True),
                    sa.Column('email_verified', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('experience', sa.Integer(), nullable=True),
                    sa.Column('verified', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('primary_specialization',
                              sa.String(), nullable=False),
                    sa.Column('secondary_focus_areas', sa.JSON(),
                              server_default='[]', nullable=True),
                    sa.Column('fee', sa.Integer(), nullable=True),
                    sa.Column('credentials', sa.String(), nullable=False),
                    sa.Column('documents', sa.Text(), nullable=True),
                    sa.Column('consults_online', sa.Boolean(),
                              server_default=sa.text('true'), nullable=True),
                    sa.Column('status', sa.Enum('AWAY', 'AVAILABLE', 'IN_PATIENT', 'UNKNOWN',
                                                name='doctor_availability_status'), server_default=sa.text("'UNKNOWN'"), nullable=False),
                    sa.Column('gender', sa.Enum('MALE', 'FEMALE',
                                                name='gender'), nullable=False),
                    sa.Column('college_studied', sa.String(),
                              server_default='NA', nullable=False),
                    sa.Column('license_number', sa.String(), nullable=False),
                    sa.Column('graduation_year', sa.Integer(), nullable=True),
                    sa.Column('bio', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('license_number')
                    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_experience'),
                    'doctor', ['experience'], unique=False)
    op.create_index(op.f('ix_doctor_fee'), 'doctor', ['fee'], unique=False)
    op.create_index(op.f('ix_doctor_name'), 'doctor', ['name'], unique=False)
    op.create_index(op.f('ix_doctor_primary_specialization'),
                    'doctor', ['primary_specialization'], unique=False)
    op.create_index(op.f('ix_doctor_verified'),
                    'doctor', ['verified'], unique=False)
    op.create_table('email_verification_token',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('user_role', sa.Enum('CLINIC_ADMIN', 'DOCTOR',
                                                   'PATIENT', name='user_role'), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('exp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('used_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_email_verification_token_hash'),
                    'email_verification_token', ['hash'], unique=True)
    op.create_index(op.f('ix_email_verification_token_user_id'),
                    'email_verification_token', ['user_id'], unique=False)
    op.create_table('patient',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('email_verified', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_patient_email'),
                    'patient', ['email'], unique=True)
    op.create_index(op.f('ix_patient_username'),
                    'patient', ['username'], unique=False)
    op.create_table('care_journey',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('reason_for_visit', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('doctor_clinics',
                    sa.Column('doctor_id', sa.UUID(), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.PrimaryKeyConstraint('doctor_id', 'clinic_id')
                    )
    op.create_table('review',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('entity_id', sa.Uuid(), nullable=False),
                    sa.Column('entity', sa.Enum('DOCTOR', 'CLINIC',
                                                name='reviewable_entity'), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('appointment_id', sa.Uuid(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.CheckConstraint('rating >= 0 AND rating <= 5',
                                       name='chk_review_rating'),
                    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_review_entity_entity_id', 'review',
                    ['entity', 'entity_id'], unique=False)
    op.create_table('schedule',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('recurrence_kind', sa.Enum(
                        'ONE_OFF', 'WEEKLY', 'MONTHLY', name='schedule_kind'), nullable=False),
                    sa.Column('timezone', sa.String(length=64),
                              server_default=sa.text("'Asia/Kolkata'"), nullable=False),
                    sa.Column('starts_on', sa.Date(), nullable=False),
                    sa.Column('ends_on', sa.Date(), nullable=True),
                    sa.Column('interval', sa.Integer(),
                              server_default='1', nullable=False),
                    sa.Column('weekdays', sa.ARRAY(
                        sa.Integer()), nullable=True),
                    sa.Column('month_days', sa.ARRAY(
                        sa.Integer()), nullable=True),
                    sa.Column('start_time', sa.Time(), nullable=False),
                    sa.Column('end_time', sa.Time(), nullable=False),
                    sa.Column('base_slot_duration',
                              sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(),
                              server_default=sa.text('true'), nullable=False),
                    sa.Column('allow_online_consultations', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('max_slots', sa.Integer(), nullable=True),
                    sa.Column('doctor_id', sa.UUID(), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.CheckConstraint('base_slot_duration >= 5',
                                       name='chk_schedule_slot_duration'),
                    sa.CheckConstraint(
                        'ends_on IS NULL OR ends_on >= starts_on', name='chk_schedule_date_range'),
                    sa.CheckConstraint(
                        'interval >= 1', name='check_schedule_interval'),
                    sa.CheckConstraint('start_time < end_time',
                                       name='chk_schedule_timing'),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_schedule_recurrence_kind'),
                    'schedule', ['recurrence_kind'], unique=False)
    op.create_table('slot',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('slot_datetime', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('is_booked', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('mode', sa.Enum('ONLINE', 'IN_PERSON', 'HYBRID',
                                              name='consultation_mode'), nullable=False),
                    sa.Column('schedule_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.CheckConstraint(
                        'duration >= 5', name='check_slot_duration'),
                    sa.ForeignKeyConstraint(
                        ['schedule_id'], ['schedule.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('schedule_id', 'slot_datetime',
                                        name='uq_schedule_datetime')
                    )
    op.create_index(op.f('ix_slot_slot_datetime'), 'slot',
                    ['slot_datetime'], unique=False)
    op.create_table('appointment',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('scheduled_date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'MISSED',
                                                name='appointment_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('slot_id', sa.UUID(), nullable=False),
                    sa.Column('doctor_id', sa.UUID(), nullable=False),
                    sa.Column('clinic_id', sa.UUID(), nullable=False),
                    sa.Column('care_journey_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['care_journey_id'], [
                                            'care_journey.id'], ),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
                    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('uq_appointment_active_slot', 'appointment', [
                    'slot_id'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointment_active_slot', table_name='appointment',
                  postgresql_where=sa.text("status != 'CANCELLED'"))
    op.drop_table('appointment')
    op.drop_index(op.f('ix_slot_slot_datetime'), table_name='slot')
    op.drop_table('slot')
    op.drop_index(op.f('ix_schedule_recurrence_kind'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index('ix_review_entity_entity_id', table_name='review')
    op.drop_table('review')
    op.drop_table('doctor_clinics')
    op.drop_table('care_journey')
    op.drop_index(op.f('ix_patient_username'), table_name='patient')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_email_verification_token_user_id'),
                  table_name='email_verification_token')
    op.drop_index(op.f('ix_email_verification_token_hash'),
                  table_name='email_verification_token')
    op.drop_table('email_verification_token')
    op.drop_index(op.f('ix_doctor_verified'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_primary_specialization'),
                  table_name='doctor')
    op.drop_index(op.f('ix_doctor_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_fee'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_experience'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_clinic_name'), table_name='clinic')
    op.drop_table('clinic')

    # Named PostgreSQL enum types are schema objects independent of the
    # tables that use them, so dropping the tables does not remove the types.
    for enum_name in (
        'appointment_status',
        'consultation_mode',
        'doctor_availability_status',
        'gender',
        'reviewable_entity',
        'schedule_kind',
        'user_role',
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
