"""initial revision.

Revision ID: e291aefc63ab
Revises: 
Create Date: 2026-05-15 21:03:28.617980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e291aefc63ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('owner', sa.String(), nullable=True),
                    sa.Column('pincode', sa.String(), nullable=True),
                    sa.Column('location', sa.VARCHAR(), nullable=False),
                    sa.Column('contact_numbers', sa.ARRAY(sa.String(length=10)),
                              server_default='{}', nullable=False),
                    sa.Column('whatsapp', sa.String(length=10), nullable=True),
                    sa.Column('facilities', sa.JSON(),
                              server_default='[]', nullable=True),
                    sa.Column('specializations', sa.JSON(),
                              server_default='[]', nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clinic_name'), 'clinic', ['name'], unique=True)
    op.create_table('doctor',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(length=10), nullable=True),
                    sa.Column('image', sa.Text(), nullable=True),
                    sa.Column('experience', sa.Integer(), nullable=True),
                    sa.Column('verified', sa.Boolean(),
                              server_default='False', nullable=False),
                    sa.Column('primary_specialization',
                              sa.String(), nullable=False),
                    sa.Column('secondary_focus_areas', sa.JSON(),
                              server_default='[]', nullable=True),
                    sa.Column('fee', sa.Integer(), nullable=True),
                    sa.Column('credentials', sa.String(), nullable=False),
                    sa.Column('documents', sa.Text(), nullable=True),
                    sa.Column('consults_online', sa.Boolean(), nullable=True),
                    sa.Column('status', sa.Enum('AWAY', 'AVAILABLE', 'IN_PATIENT', 'UNKNOWN',
                                                name='doctor_availability_status'), server_default=sa.text("'UNKNOWN'"), nullable=True),
                    sa.Column('gender', sa.Enum('MALE', 'FEMALE',
                                                name='gender'), nullable=False),
                    sa.Column('college_studied', sa.String(),
                              server_default='NA', nullable=True),
                    sa.Column('license_number', sa.String(), nullable=False),
                    sa.Column('graduation_year', sa.Integer(), nullable=True),
                    sa.Column('bio', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('license_number')
                    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_name'), 'doctor', ['name'], unique=False)
    op.create_index(op.f('ix_doctor_primary_specialization'),
                    'doctor', ['primary_specialization'], unique=False)
    op.create_table('patient',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_patient_email'),
                    'patient', ['email'], unique=True)
    op.create_table('doctor_clinics',
                    sa.Column('doctor_id', sa.Uuid(), nullable=False),
                    sa.Column('clinic_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.PrimaryKeyConstraint('doctor_id', 'clinic_id')
                    )
    op.create_table('review',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('doctor_id', sa.Uuid(), nullable=True),
                    sa.Column('clinic_id', sa.Uuid(), nullable=True),
                    sa.Column('patient_id', sa.Uuid(), nullable=False),
                    sa.Column('appointment_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.CheckConstraint(
                        '(doctor_id IS NOT NULL) OR (clinic_id IS NOT NULL)', name='chk_review_entity_presence'),
                    sa.CheckConstraint('rating >= 0 AND rating <= 5',
                                       name='chk_review_rating'),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('appointment_id')
                    )
    op.create_table('schedule',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('weekdays', sa.ARRAY(sa.Integer()),
                              server_default='{}', nullable=False),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='True', nullable=False),
                    sa.Column('start_time', sa.Time(
                        timezone=True), nullable=False),
                    sa.Column('end_time', sa.Time(
                        timezone=True), nullable=True),
                    sa.Column('base_slot_duration',
                              sa.Integer(), nullable=False),
                    sa.Column('doctor_id', sa.Uuid(), nullable=False),
                    sa.Column('clinic_id', sa.Uuid(), nullable=False),
                    sa.CheckConstraint('start_time < end_time',
                                       name='chk_schedule_timing'),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('slot',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('is_booked', sa.Boolean(), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=True),
                    sa.Column('slot_datetime', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('mode', sa.Enum('ONLINE', 'IN_PERSON', name='consultation_mode'),
                              server_default=sa.text("'IN_PERSON'"), nullable=True),
                    sa.Column('schedule_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['schedule_id'], ['schedule.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('appointment',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('scheduled_date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'MISSED',
                                                name='appointment_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
                    sa.Column('patient_id', sa.Uuid(), nullable=False),
                    sa.Column('slot_id', sa.Uuid(), nullable=False),
                    sa.Column('doctor_id', sa.Uuid(), nullable=False),
                    sa.Column('clinic_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
                    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
                    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slot_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('slot')
    op.drop_table('schedule')
    op.drop_table('review')
    op.drop_table('doctor_clinics')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_primary_specialization'),
                  table_name='doctor')
    op.drop_index(op.f('ix_doctor_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_clinic_name'), table_name='clinic')
    op.drop_table('clinic')
    # ### end Alembic commands ###
